[package]
name = "qb_finder_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
qb_finder_core = { path = "../qb_finder_core/" }
itertools = "0.14.0"
srs-4l = { workspace = true }
rustc-hash = "2.1.1"
