[workspace]
members = [
    "qb_finder_cli",
    "qb_finder_core",
    "qb_finder_web",
    "py_qbf"
]
resolver = "2"

[workspace.dependencies]
compute = { git = "https://github.com/wirelyre/tetra-tools" }
srs-4l = { git = "https://github.com/wirelyre/tetra-tools" }
